#!/bin/sh

ipaddr=`(uci -q get network.lan.ipaddr)`
secret=`(head -c 16 /dev/urandom | md5sum | cut -c1-8)`

uci -q batch << EOF >"/dev/null"
    set songbox.experimental.external_controller="$ipaddr:9090"
    set songbox.experimental.secret=$secret
    commit songbox
EOF

sed -i '/update_rule-set.sh/d' /etc/crontabs/root
echo "0 0 * * 0 sh /usr/libexec/rpcd/songbox/update_rule-set.sh" >> /etc/crontabs/root
return 0